name: Setup Node
description: Setup Node from .nvmrc

runs:
  using: composite
  steps:
    - name: Read Node version from .nvmrc
      shell: bash
      run: echo "name=NVMRC::$(cat .nvmrc)" >> $GITHUB_OUTPUT
      id: nvm

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ steps.nvm.outputs.NVMRC }}
        cache: yarn
