---

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_VERSION: "18.06"
  IMAGE_INFRA_BASE_NAME: "infra/images-docker"

stages:
  - "Build docker build image"
  - "Code Quality"
  - "Build archifiltre"


Quality:
  stage: "Code Quality"
  image: node:12-alpine
  before_script:
    - yarn --frozen-lockfile
  scripts:
    - yarn lint
    - yarn test


Build:
  stage: "Build"
  image: node:12-alpine
  before_script:
    - yarn --frozen-lockfile
  scripts:
    - yarn buildProd
  artifacts:
    paths:
    - dist/mac-x64/archifiltre-1.0.0.dmg
    expire_in: 1 week