---

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_VERSION: "18.06"
  IMAGE_INFRA_BASE_NAME: "infra/images-docker"
  IMAGE_NAME: "archifiltre-build"

stages:
  - "Build docker build image"
  - "Code Quality"
  - "Build archifiltre"


Docker:
  stage: "Build docker build image"
  services:
    - docker:$DOCKER_VERSION-dind
  image: docker:$DOCKER_VERSION
  before_script:
    - echo "$CI_JOB_TOKEN" | docker login $CI_REGISTRY -u gitlab-ci-token --password-stdin
  script:
    - docker pull $CI_REGISTRY_IMAGE$IMAGE_NAME:master || true
    - docker build --cache-from $CI_REGISTRY_IMAGE$IMAGE_NAME:master -t $CI_REGISTRY_IMAGE$IMAGE_NAME:master - < Dockerfile
    - docker push $CI_REGISTRY_IMAGE$IMAGE_NAME:master


Quality:
  stage: "Code Quality"
  image: node:12-alpine
  before_script:
    - yarn --frozen-lockfile
  script:
    - yarn lint
    - yarn test

Build:
  stage: "Build archifiltre"
  image: $IMAGE_NAME:master
  before_script:
    - yarn --frozen-lockfile
  script:
    - yarn buildProd
  artifacts:
    paths:
    - dist/mac-x64/archifiltre-1.0.0.dmg
    expire_in: 1 week
