---
variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_VERSION: "18.06"
  IMAGE_INFRA_BASE_NAME: "infra/images-docker"
  IMAGE_NAME: "archifiltre-build"

stages:
  - "Build docker build image"
  - "Code Quality"
  - "Build archifiltre"

Docker:
  stage: "Build docker build image"
  services:
    - docker:$DOCKER_VERSION-dind
  image: docker:$DOCKER_VERSION
  before_script:
    - echo "$CI_JOB_TOKEN" | docker login $CI_REGISTRY -u gitlab-ci-token --password-stdin
  script:
    - docker pull $CI_REGISTRY_IMAGE:master || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:master -t $CI_REGISTRY_IMAGE:master - < Dockerfile
    - docker push $CI_REGISTRY_IMAGE:master

Quality:
  stage: "Code Quality"
  image: $CI_REGISTRY_IMAGE:master
  before_script:
    - yarn --frozen-lockfile
  script:
    - yarn lint
    - yarn test
  cache:
    key: ${CI_JOB_NAME}
    paths:
      - node_modules/
      - $HOME/.cache/electron

Build:
  stage: "Build archifiltre"
  image: $CI_REGISTRY_IMAGE:master
  before_script:
    - yarn --frozen-lockfile
  script:
    - yarn build-prod
    - git remote add upstream https://github.com/${CI_PROJECT_PATH}
    - git fetch upstream +refs/pull/*/merge:refs/remotes/origin/pr/*
    - export PR_ID=$(git ls-remote upstream refs/pull/[0-9]*/head | grep ${CI_COMMIT_SHA} | cut -d '/' -f3)
    - |
      curl --request POST \
        --url https://${GITHUB_TOKEN}@api.github.com/repos/SocialGouv/archifiltre/issues/${PR_ID}/comments \
        --header 'content-type: application/json' \
        --data '{"body": "Download Artifacts :\n\n - [win-ia32]('${CI_PROJECT_URL}'/-/jobs/'${CI_JOB_ID}'/artifacts/raw/dist/win-ia32/archifiltre%2013.0.0.exe)\n - [win-x64]('${CI_PROJECT_URL}'/-/jobs/'${CI_JOB_ID}'/artifacts/raw/dist/win-x64/archifiltre%2013.0.0.exe)\n  - [linux-x64]('${CI_PROJECT_URL}'/-/jobs/'${CI_JOB_ID}'/artifacts/raw/dist/linux-x64/archifiltre%2013.0.0.AppImage)"}'
  artifacts:
    paths:
      - dist/win-ia32/archifiltre 13.0.0.exe
      - dist/win-x64/archifiltre 13.0.0.exe
      - dist/linux-x64/archifiltre 13.0.0.AppImage
    expire_in: 1 week
  cache:
    key: ${CI_JOB_NAME}
    paths:
      - node_modules/
      - $HOME/.cache/electron
      - $HOME/.cache/electron-builder
  only:
    - branches
  except:
    - master

