---
variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_VERSION: "18.06"
  IMAGE_INFRA_BASE_NAME: "infra/images-docker"
  IMAGE_NAME: "archifiltre-build"

stages:
  - "Build docker build image"
  - "Code Quality"
  - "Build for branch"
  - "Build for master"
  - "Build binaries for branch"

Docker:
  stage: "Build docker build image"
  services:
    - docker:$DOCKER_VERSION-dind
  image: docker:$DOCKER_VERSION
  before_script:
    - echo "$CI_JOB_TOKEN" | docker login $CI_REGISTRY -u gitlab-ci-token --password-stdin
  script:
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG - < Dockerfile
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

Quality:
  stage: "Code Quality"
  image: $CI_REGISTRY_IMAGE:master
  before_script:
    - yarn --frozen-lockfile
  script:
    - yarn lint
    - yarn test
  cache:
    key: ${CI_JOB_NAME}
    paths:
      - node_modules/
      - $HOME/.cache/electron

Build-branch:
  stage: "Build for branch"
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  before_script:
    - yarn --frozen-lockfile
  script:
    - cp .env.prod .env
    - yarn prepare-prod
  cache:
    key: ${CI_JOB_NAME}
    paths:
      - node_modules/
      - $HOME/.cache/electron
      - $HOME/.cache/electron-builder
  only:
    - branches
  except:
    - master

Build-master:
  stage: "Build for master"
  image: $CI_REGISTRY_IMAGE:master
  before_script:
    - yarn --frozen-lockfile
  script:
    - cp .env.prod .env
    - yarn prepare-prod
    - yarn win64
    - export ARCHIFILTRE_VERSION="$(node -e 'console.log(require("./package.json").version)')"
    - mv dist/win-x64/archifiltre\ $ARCHIFILTRE_VERSION.exe dist/win-x64/archifiltre-master.exe
  artifacts:
    paths:
      - dist/win-x64/archifiltre-master.exe
    expire_in: 1 week
  cache:
    key: ${CI_JOB_NAME}
    paths:
      - node_modules/
      - $HOME/.cache/electron
      - $HOME/.cache/electron-builder
  only:
    - master

Build-branch-bins:
  stage: "Build binaries for branch"
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  before_script:
    - yarn --frozen-lockfile
  script:
    - cp .env.prod .env
    - yarn prepare-prod
    - yarn win32
    - yarn win64
    - yarn linux
    - export ARCHIFILTRE_VERSION="$(node -e 'console.log(require("./package.json").version)')"
    - git remote add upstream https://github.com/${CI_PROJECT_PATH}
    - git fetch upstream +refs/pull/*/merge:refs/remotes/origin/pr/*
    - export PR_ID=$(git ls-remote upstream refs/pull/[0-9]*/head | grep ${CI_COMMIT_SHA} | cut -d '/' -f3 | tail -1)
    - |
      curl --request POST \
        --url https://${GITHUB_TOKEN}@api.github.com/repos/SocialGouv/archifiltre/issues/${PR_ID}/comments \
        --header 'content-type: application/json' \
        --data '{"body": "Download Artifacts :\n\n - [win-ia32]('${CI_PROJECT_URL}'/-/jobs/'${CI_JOB_ID}'/artifacts/raw/dist/win-ia32/archifiltre%20'${ARCHIFILTRE_VERSION}'.exe)\n - [win-x64]('${CI_PROJECT_URL}'/-/jobs/'${CI_JOB_ID}'/artifacts/raw/dist/win-x64/archifiltre%20'${ARCHIFILTRE_VERSION}'.exe)\n  - [linux-x64]('${CI_PROJECT_URL}'/-/jobs/'${CI_JOB_ID}'/artifacts/raw/dist/linux-x64/archifiltre-'${ARCHIFILTRE_VERSION}'.AppImage)"}'
  artifacts:
    paths:
      - dist/win-ia32/archifiltre *.exe
      - dist/win-x64/archifiltre *.exe
      - dist/linux-x64/archifiltre-*.AppImage
    expire_in: 1 week
  cache:
    key: ${CI_JOB_NAME}
    paths:
      - node_modules/
      - $HOME/.cache/electron
      - $HOME/.cache/electron-builder
  when: manual