---

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_VERSION: "18.06"
  IMAGE_INFRA_BASE_NAME: "infra/images-docker"
  IMAGE_NAME: "archifiltre-build"

stages:
  - "Build docker build image"
  - "Code Quality"
  - "Build archifiltre"


Docker:
  stage: "Build docker build image"
  services:
    - docker:dind
  image: docker:latest
  before_script:
    - echo "$CI_JOB_TOKEN" | docker login $CI_REGISTRY -u gitlab-ci-token --password-stdin
  script:
    - >
      if [[ -n "${CI_COMMIT_TAG}" ]]; then
        export TAG=$(printf "${CI_COMMIT_TAG}" | sed "s/^v//")
      else
        export TAG=$CI_COMMIT_REF_SLUG
      fi
    #
    - docker pull $IMAGE_NAME:$CI_COMMIT_BEFORE_SHA || true
    - docker pull $IMAGE_NAME:$TAG || true
    - docker pull $IMAGE_NAME:master || true
    - docker build --cache-from $IMAGE_NAME:master -t $IMAGE_NAME:$CI_COMMIT_SHA -t $IMAGE_NAME:$TAG - < Dockerfile
    - docker push $IMAGE_NAME:$CI_COMMIT_SHA
    - docker push $IMAGE_NAME:$TAG

Quality:
  stage: "Code Quality"
  image: node:12-alpine
  before_script:
    - yarn --frozen-lockfile
  script:
    - yarn lint
    - yarn test

Build:
  stage: "Build archifiltre"
  image: node:12-alpine
  before_script:
    - yarn --frozen-lockfile
  script:
    - yarn buildProd
  artifacts:
    paths:
    - dist/mac-x64/archifiltre-1.0.0.dmg
    expire_in: 1 week
