name: Scénario de Test
description: Confirmation d'un bogue par exécution d'un test e2e.
labels:
  - e2e
body:
  - type: input
    id: bug
    attributes:
      label: Bogue associé
      description: Copier l'url du bogue associé (si applicable)
      placeholder: SocialGouv/archifiltre-docs#<number>
      value: SocialGouv/archifiltre-docs#
    validations:
      required: true
  - type: textarea
    id: describe
    validations:
      required: true
    attributes:
      label: Scenario
      description: Given/When/Then
  - type: textarea
    attributes:
      label: Captures d'écran (si applicable)
      placeholder: |
        # Copiez-collez directement vos images après capture d'écran
        # ou utilisez une image markdown "![nom-de-mon-image](https://url-de-mon-image)" si vous l'avez uploadée vous même.
  - type: dropdown
    id: os
    validations:
      required: true
    attributes:
      label: Système d'exploitation
      multiple: true
      options:
        - Windows
        - Linux
        - OSX
        - Tous
  - type: textarea
    id: misc
    attributes:
      label: Informations complémentaires
      placeholder: Ajoutez toutes autres données qui pourraient potentiellement aider à l'écriture du scénario en test.
