name: CI
on:
  push:
    branches: [main, dev, beta]
  pull_request:
    branches: [main, dev]

jobs:
  quality:
    name: Quality Control on Node (ubuntu-latest)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: ./.github/actions/setup-node
      - name: Yarn install
        run: yarn --frozen-lockfile --perfer-offline

      - name: Test if code compile
        run: yarn compile --no-progress --display-error-details
        env:
          SKIP_SENTRY_UPLOAD: 1
          TRACKER_MATOMO_ID_SITE: ${{ secrets.TRACKER_MATOMO_ID_SITE }}
          TRACKER_MATOMO_URL: ${{ secrets.TRACKER_MATOMO_URL }}
          TRACKER_PROVIDER: ${{ secrets.TRACKER_PROVIDER }}
          TRACKER_POSTHOG_API_KEY: ${{ secrets.TRACKER_POSTHOG_API_KEY }}
          TRACKER_POSTHOG_URL: ${{ secrets.TRACKER_POSTHOG_URL }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_URL: ${{ secrets.SENTRY_URL }}
          ARCHIFILTRE_SITE_URL: ${{ secrets.ARCHIFILTRE_SITE_URL }}
          FORCE_TRACKING: false

      - name: Lint
        run: yarn lint

      - name: Unit tests
        run: yarn test --ci --coverage

      - name: Send test coverage to codecov
        continue-on-error: true
        uses: codecov/codecov-action@v2
