name: Test Workflow
on: push

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    if: "${{ github.event.workflow_run.conclusion == 'success' }}
      || ${{ github.event_name == 'schedule'}}
      || (${{ github.event_name == 'workflow_dispatch' }} && contains('refs/heads/main,refs/heads/beta,refs/heads/dev', github.ref))"
    outputs:
      current-version: ${{ steps.compile.outputs.current-version }}
      next-version: ${{ steps.compile.outputs.next-version }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ env.GITHUB_REF_OVERRIDE }}
      - name: Setup Node
        uses: ./.github/actions/setup-node
      - name: Yarn install
        run: yarn add semantic-release
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.SOCIALGROOVYBOT_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.SOCIALGROOVYBOT_GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_push_gpgsign: false
          git_tag_gpgsign: true
      - id: compile
        name: Compile
        run: |
          export PATH="$(pwd)/.github/bin/:$PATH"
          # override because of "env-ci" used by semantic-release
          # GITHUB_REF should not be default branch when "workflow_run" event is triggered
          export GITHUB_REF=$GITHUB_REF_OVERRIDE
          echo ::set-output name=current-version::$(node -e "console.log(require('./package.json').version)")
          yarn semantic-release
          echo ::set-output name=next-version::$(node -e "console.log(require('./package.json').version)")
        env:
          ARCHIFILTRE_RELEASE_MODE: version
          TRACKER_MATOMO_ID_SITE: ${{ secrets.TRACKER_MATOMO_ID_SITE }}
          TRACKER_MATOMO_URL: ${{ secrets.TRACKER_MATOMO_URL }}
          TRACKER_PROVIDER: ${{ secrets.TRACKER_PROVIDER }}
          TRACKER_POSTHOG_API_KEY: ${{ secrets.TRACKER_POSTHOG_API_KEY }}
          TRACKER_POSTHOG_URL: ${{ secrets.TRACKER_POSTHOG_URL }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_URL: ${{ secrets.SENTRY_URL }}
          ARCHIFILTRE_SITE_URL: ${{ secrets.ARCHIFILTRE_SITE_URL }}
          FORCE_TRACKING: false
      - name: Echo
        run: |
          echo "${{steps.compile.outputs.current-version}}"
          echo "${{steps.compile.outputs.next-version}}"
